name       : vigra
version    : 1.11.1
release    : 8
source     :
    - https://github.com/ukoethe/vigra/releases/download/Version-1-11-1/vigra-1.11.1-src.tar.gz : a5564e1083f6af6a885431c1ee718bad77d11f117198b277557f8558fa461aaf
license    : MIT
component  : multimedia.library
summary    : C++ library for image analysis
description: |
    VIGRA is a computer vision library that puts its main emphasis on flexible algorithms, because algorithms represent the principal know-how of this field. The library was consequently built using generic programming as introduced by Stepanov and Musser and exemplified in the C++ Standard Template Library. By writing a few adapters (image iterators and accessors) you can use VIGRA's algorithms on top of your data structures, within your environment. Alternatively, you can also use the data structures provided within VIGRA, which can be easily adapted to a wide range of applications. VIGRA's flexibility comes almost for free: Since the design uses compile-time polymorphism (templates), performance of the compiled program approaches that of a traditional, hand tuned, inflexible, solution.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - libboost-devel
setup      : |
    %cmake -DWITH_OPENEXR=1 \
        -DWITH_BOOST_GRAPH=1 \
        -DDOCINSTALL=share/doc \
        .
build      : |
    %make
install    : |
    %make_install
